sudo: required
services:
  - docker

before_install:
  - docker build -t gbutchers/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run gbutchers/react-test npm run test -- --coverage

after_success:
  - docker build -t gbutchers/multi-client ./client  
  - docker build -t gbutchers/multi-nginx ./nginx  
  - docker build -t gbutchers/multi-server ./server  
  - docker build -t gbutchers/multi-worker ./worker  
# Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push those images to the Docker Hub Repo
  - docker push gbutchers/multi-client
  - docker push gbutchers/multi-nginx
  - docker push gbutchers/multi-server
  - docker push gbutchers/multi-worker
  
# deploy:
#   provider: elasticbeanstalk
#   region: eu-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-eu-west-1-440130807111
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY